# scoring function and search settings
scoring_function chemplp
search_speed speed2

# input files
protein_file MAPK1_AF_model.mol2 
ligand_file redock_ligand.mol2 

# output to results directory
output_dir results_af

# binding site definition
bindingsite_center 1.34299 17.3648 40.9828
bindingsite_radius 12.9007

# cluster algorithm
cluster_structures 10
cluster_rmsd 2.0

# write output
write_multi_mol2 1
write_ranking_links 0
write_protein_bindingsite 0
write_protein_conformations 0
write_merged_protein 0
write_per_atom_scores 1